### ISSUE TITLE
[Bug] Dismissing Texture tab modals without pressing Cancel doesn't properly close them

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#121]
### What happened?

Opening a modal while in the Textures tab, closing it by clicking away from the window and then opening any other one results in both of them being opened at once. This can stack, and has the additional effect of completely disabling some of the modal-opening buttons when you repeat the process enough times.

### To reproduce

1. Go to the Textures tab
2. Click on any of the blue buttons to open a modal
3. Dismiss the window by clicking away from it (without pressing Cancel)
4. Open any other modal
5. Both of them are opened at once
6. Repeat enough times with all of the available modals on the page
7. See that some buttons stop performing their intended function

### Screenshot(s)

![obrazek](https://github.com/Faithful-Resource-Pack/App/assets/59484948/3ffa8b69-43d7-4d75-89df-de678f878ba6)

### Browser name and version

Firefox 120

### Notes

The issue is fixed with a page refresh, after which the "count" resets and you can open any modal again (and get the bug to happen again if you dismiss the modals without pressing Cancel).  
This could be a web app-wide problem, but it's most apparent in the Textures tab.

**Comment by 3vorp** [comment]
I've noticed this problem ever since 662e1aeaaddba82178ece458d9ed3f9668e51920 was implemented.

**Comment by Pomi108** [comment]
Fairly sure I've seen it happen even before that

**Comment by 3vorp** [comment]
<img width="607" alt="Screen Shot 2024-01-16 at 9 45 11 PM" src="https://github.com/Faithful-Resource-Pack/App/assets/75297863/5a35ba3b-4a70-4440-b6ce-5fdc2a22ddb3">

Found the problem, not sure how to solve it...

**Comment by TheRolfFR** [comment]
I know how, I didn't know when I started how to make a proper [custom v-model on a custom component](https://www.digitalocean.com/community/tutorials/how-to-add-v-model-support-to-custom-vue-js-components), but this should have been used since the beginning to manipulate v-dialog v-model.

If you want to know how to fix this, I already fixed some of the modals **in the codebase**, so look for code that plays with things like ``this.$emit('input', this.<internal_data_member>)``, ``watch`` section for the ``value`` property and ``<internal_data_member>``
