### ISSUE TITLE
[REQUEST] - Textures excluded from /missing texture list in gallery

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#16]
Right now, textures like redstone_dust_overlay (which is fully transparent) are shown as not done in the gallery.
![Snímek obrazovky 2022-01-01 v 17 28 21](https://user-images.githubusercontent.com/59484948/147855163-b3d04a9b-ead4-442d-bcff-1f845ea282ca.png)

This can be misleading. I suggest that for textures that are excluded from the /missing command, we simply display the vanilla texture instead.

Alternatively, we could hide textures like these from displaying completely.

**Comment by RobertRR11** [comment]
What about just removing them from the database completely, because clearly we will never use them in any way

**Comment by Pomi108** [comment]
well I would like to retain the ability to search for them using the bot though

**Comment by 3vorp** [comment]
we could probably fetch from https://raw.githubusercontent.com/faithful-resource-pack/complibot/main/json/blacklisted_textures.json and filter out stuff in the same way as /missing (by checking if any of these entries is included within the path), but this may be computationally expensive since you need to check every path of every single texture

**Comment by 3vorp** [comment]
completed with https://github.com/Faithful-Resource-Pack/API/commit/6f847fd2a0faeafb4acbf052756c8221a9b0b059
