### ISSUE TITLE
[Bug] Versions 1.4.6 and b1.7.3 don't work with the gallery

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#92]
### What happened?

Even though all the paths are correct, the gallery doesn't display any textures from versions 1.4.6 and b1.7.3. Not even the 16x ones.

### To reproduce

1. Go to the gallery
2. Select 1.4.6 or b1.7.3 as the version
3. See that no texture is displayed

### Screenshot(s)

![obrazek](https://user-images.githubusercontent.com/59484948/182340198-1c0042be-b371-4242-a9ef-e9f6da6a1819.png)

### Browser name and version

Firefox 103.0

### Notes

Versions 1.6.4 and above work fine.

**Comment by TheRolfFR** [comment]
Images still lead to https://raw.githubusercontent.com/CompliBot/Default-Java/1.19.2/assets/realms/textures/gui/realms/accept_icon.png and @CompliBot user was deleted https://github.com/CompliBot so the link doesn't for newly added packs

**Comment by TheRolfFR** [comment]
For 32x, there is a problem with b1.7.3 path because in https://raw.githubusercontent.com/Faithful-Resource-Pack/Faithful-Java-32x/b1.7.3/assets/minecraft/environment/snow.png (id 1240) there is a ``assets/minecraft`` path when they should not be one, 
https://raw.githubusercontent.com/Faithful-Resource-Pack/Faithful-Java-32x/b1.7.3/environment/snow.png.

All of these issues are settings and API related.
the settings can be modified in the webapp, the api issues are a little trickier as a code bit should be made more robust:
https://github.com/Faithful-Resource-Pack/API/blob/845577fe68819afaa7eda18beae4499ab2f17578/src/v2/service/gallery.service.ts#L27-L30

I have a problem though: snow uses the same use with an asset non null but a different path
![image](https://user-images.githubusercontent.com/18086786/184476507-344b25c6-7c2b-407a-86d5-99f2049ce7bd.png)
thus adding the ``assets/minecraft`` string.

But how do you think it's the cleanest solution ? Solve that by adding make another use, or specific code-based solution for some minecraft versions?

**Comment by Pomi108** [comment]
why is `assets/minecraft` being added in the first place? The paths in the db should be used in the state they're saved in

**Comment by Pomi108** [comment]
Also, this must be a recent change, because I remember the old versions working properly

**Comment by TheRolfFR** [comment]
> why is `assets/minecraft` being added in the first place? The paths in the db should be used in the state they're saved in

Is it a lazy java/bedrock tweak at the beginning someone made?

> Also, this must be a recent change, because I remember the old versions working properly

Mmmh, investigating with git blame...
Found some things : 
https://github.com/Faithful-Resource-Pack/API/blame/main/src/v2/firestorm/textures/index.ts#L61-L63
https://github.com/Faithful-Resource-Pack/API/blame/main/src/v2/firestorm/textures/index.ts#L89-L90

@Juknum knows better

**Comment by RobertRR11** [comment]
> Images still lead to [CompliBot/Default-Java@`1.19.2`/assets/realms/textures/gui/realms/accept_icon.png (raw)](https://raw.githubusercontent.com/CompliBot/Default-Java/1.19.2/assets/realms/textures/gui/realms/accept_icon.png) and @CompliBot user was deleted [@CompliBot](https://github.com/CompliBot) so the link doesn't for newly added packs

No it wasn't deleted, I renamed it, but I didn't know that it won't redirect

**Comment by Juknum** [comment]
> why is `assets/minecraft` being added in the first place? The paths in the db should be used in the state they're saved in

That's because in the current way textures are stored in the database, the assets folder name is stored within the use of the texture, thus the use doesn't determine in which version the texture is used, so the path can't be determined (is wrong) when the assets folder system wasn't implemented yet (for 1.6 and below versions)

```jsonc
{
    "uses": [
        {
            "id": "720a",
            "name": "",
            "texture": 720,
            "edition": "java",
            "assets": "minecraft" // asset folder, could be "minecraft" or "realms" or any mods folder
        }
    ],
    "paths": [
        {
            "id": "6096bcd980ad4",
            "use": "720a",
            "name": "textures/block/stone.png", // path to the texture from the assets folder
            "mcmeta": false,
            "versions": [
                "1.19.2",
                "1.18.2",
                "1.17.1",
                "1.16.5",
                "1.15.2",
                "1.14.4",
                "1.13.2"
            ]
        }
    ]
}
```

Then, when asking for the whole URL the API returns the use assets field & the path name field combined (which broke for versions where the assets system does not exist)

@TheRolfFR in the mentioned lines, there is a temp fix for realms textures that are still written as "minecraft" assets where they should be "realms" instead. [API endpoint here](https://api.faithfulpack.net/v2/uses/raw)

**Comment by TheRolfFR** [comment]
> No it wasn't deleted, I renamed it, but I didn't know that it won't redirect

It currently still redirects previously hit URLs with textures but I think that since b1.7.3 and 1.4.6 are new and didn't exist at that time, they aren't

**Comment by Pomi108** [comment]
Would I be able to fix this myself if I made separate uses for the old versions?

**Comment by TheRolfFR** [comment]
Sure but it would be painful for you, so the question is, Solve that by adding make another use, or specific code-based solution for some minecraft versions?

And I needed everyone answer to this question @Juknum @RobertRR11 

In the meantime, don't do anything because I feel like it's for all versions where there is still no assets folder (we need to know what version) and we could fix that with code.

**Comment by 3vorp** [comment]
fixed with recent api changes
